server:
  port: 8091

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/promeet_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: saloum
    driver-class-name: com.mysql.cj.jdbc.Driver

  mail:
    host: smtp.gmail.com
    port: 587
    username: sensaloumdev@gmail.com
    password: jfrp nuqc rjiq olhg
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  jpa:
    hibernate:
      ddl-auto: update # update, create, validate, none selon usage
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  jackson:
    serialization:
      write-dates-as-timestamps: false  # Pour bien gérer OffsetDateTime, LocalDateTime au format ISO8601

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG


jwt:
  secret: "4s9n02TsBXRNxNXHjT1B1tK4MydcyKR1Hdv7Tg/73jE="
  access-token-expiration-ms: 900000    # 15 min
  refresh-token-expiration-ms: 604800000  # 7 jours



afribapay:
  api:
    url: ${AFRIBAPAY_API_URL:https://api-sandbox.afribapay.com/v1}
    user: ${AFRIBAPAY_API_USER:pk_sandbox_6c47d814-8647-4201-a650-a2afff6247ae}
    key: ${AFRIBAPAY_API_KEY:sk_sandbox_NRwBOQDCunv3C1W4PK9kfH04TI6738Q3gBx}
    merchant-key: ${AFRIBAPAY_MERCHANT_KEY:mk_Dv2c9Us240920061620}
